### ISSUE TITLE
how view layer call presenter layer ？

### ISSUE THREAD

**Issue by wenjiahui** [wongcain/MVP-Simple-Demo#1]
In the demo, Presenter hold a Vu instance, so Presenter can directly call Vu's public method. But Vu doesn't know any presenters. Does it mean that user action should be sent by callback or eventbus event ?

**Comment by wongcain** [comment]
Yes, that is right.  In my approach, a Vu should be driven by a presenter and have no external dependencies (including the event bus and the presenter).  I use callbacks exclusively to communicate back to the presenter.

**Comment by wongcain** [comment]
It's also worth mentioning that instead of a callback, you can have your Vu define a Listener Interface and a public method for setting the listener.  Then the presenter can implement the interface and set itself as the listener.   Another option is to expose an Observable via a public method.
