### ISSUE TITLE
How to do with onCreateOptionsMenu() and onOptionsItemSelected()

### ISSUE THREAD

**Issue by kaleai** [wongcain/MVP-Simple-Demo#2]
The imp cann't include menu's functions.

**Comment by wongcain** [comment]
I haven't quite worked out how to separate out the "View" aspect of menus.  However, all the capabilities of the Activities are intact.  You can implement onCreateOptionsMenu() and onOptionsItemSelected() just as you would with a generic Activity.

**Comment by Yom9c** [comment]
有些问题想请教您一下，您有QQ或者其他联系方式吗

**Comment by kaleai** [comment]
hi,Yom9c.If you want to discuss about the mvp,you can writ your qq or gmail here.I think author could see it.

**Comment by wongcain** [comment]
Yes, please post your questions here (pref in English).  I'd be happy to answer what I can.  Thanks.
